[package]
name = "jgenesis-native-driver"
version = "0.7.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
clap = ["dep:clap"]

[dependencies]
jgenesis-proc-macros = { path = "../../common/jgenesis-proc-macros" }
jgenesis-common = { path = "../../common/jgenesis-common" }

gb-core = { path = "../../backend/gb-core" }
gba-core = { path = "../../backend/gba-core" }
genesis-core = { path = "../../backend/genesis-core" }
nes-core = { path = "../../backend/nes-core" }
s32x-core = { path = "../../backend/s32x-core" }
segacd-core = { path = "../../backend/segacd-core" }
smsgg-core = { path = "../../backend/smsgg-core" }
snes-core = { path = "../../backend/snes-core" }

gb-config = { path = "../../config/gb-config" }
gba-config = { path = "../../config/gba-config" }
nes-config = { path = "../../config/nes-config" }
smsgg-config = { path = "../../config/smsgg-config" }
snes-config = { path = "../../config/snes-config" }

egui-sdl2-platform = { path = "../egui-sdl2-platform" }
jgenesis-native-config = { path = "../jgenesis-native-config" }
jgenesis-renderer = { path = "../jgenesis-renderer", features = ["serde", "ttf"] }

arrayvec = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true, optional = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
rustc-hash = { workspace = true }
sdl2 = { workspace = true }
sevenz-rust = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true
