[package]
name = "jgenesis-native-driver"
version = "0.6.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgenesis-proc-macros = { path = "../../jgenesis-proc-macros" }
jgenesis-renderer = { path = "../jgenesis-renderer" }
jgenesis-common = { path = "../../jgenesis-common" }

gb-core = { path = "../../backend/gb-core" }
genesis-core = { path = "../../backend/genesis-core" }
nes-core = { path = "../../backend/nes-core" }
segacd-core = { path = "../../backend/segacd-core" }
smsgg-core = { path = "../../backend/smsgg-core" }
snes-core = { path = "../../backend/snes-core" }

anyhow = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
egui = { workspace = true }
egui_wgpu_backend = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
serde = { workspace = true }
sdl2 = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_Media"] }

[lints]
workspace = true
