[package]
name = "jgenesis-native-driver"
version = "0.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
clap = ["dep:clap"]
gba = []

[dependencies]
jgenesis-proc-macros = { path = "../../common/jgenesis-proc-macros" }
jgenesis-renderer = { path = "../jgenesis-renderer", features = ["serde", "ttf"] }
jgenesis-common = { path = "../../common/jgenesis-common" }
egui-sdl2-platform = { path = "../egui-sdl2-platform" }

gb-core = { path = "../../backend/gb-core", features = ["serde"] }
gba-core = { path = "../../backend/gba-core" }
genesis-core = { path = "../../backend/genesis-core", features = ["serde"] }
nes-core = { path = "../../backend/nes-core", features = ["serde"] }
s32x-core = { path = "../../backend/s32x-core" }
segacd-core = { path = "../../backend/segacd-core" }
smsgg-core = { path = "../../backend/smsgg-core", features = ["serde"] }
snes-core = { path = "../../backend/snes-core", features = ["serde"] }

arrayvec = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true, optional = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
rustc-hash = { workspace = true }
sdl2 = { workspace = true }
serde = { workspace = true }
sevenz-rust = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true
