doc-valid-idents = [
    "KHz",
    "MHz",
    "µPD77C25",
    "µPD96050",
    "HBlank",
    "VBlank",
    "iNES",
    "UxROM",
    "AxROM",
    "GxROM",
    "AppImage",
    "ARMv3",
    "ARMv4",
    "ARMv4T",
    "..",
]
