[package]
name = "spc700-emu"
version = "0.7.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgenesis-common = { path = "../../common/jgenesis-common" }

bincode = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
