[package]
name = "sh2-emu"
version = "0.1.0"
edition = "2024"

[dependencies]
jgenesis-common = { path = "../../common/jgenesis-common" }

bincode = { workspace = true, features = ["derive"] }
log = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
