[package]
name = "gb-core"
version = "0.6.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serde = ["dep:serde"]

[dependencies]
jgenesis-common = { path = "../../jgenesis-common" }
jgenesis-proc-macros = { path = "../../jgenesis-proc-macros" }

bincode = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[lints]
workspace = true
