[package]
name = "cdrom"
version = "0.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgenesis-proc-macros = { path = "../jgenesis-proc-macros" }

bincode = { workspace = true, features = ["derive"] }
chd = { workspace = true, features = ["unstable_lending_iterators"] }
crc = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
