[package]
name = "segacd-core"
version = "0.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdrom = { path = "../../common/cdrom" }
genesis-core = { path = "../genesis-core" }
jgenesis-proc-macros = { path = "../../common/jgenesis-proc-macros" }
jgenesis-common = { path = "../../common/jgenesis-common" }
m68000-emu = { path = "../../cpu/m68000-emu" }
smsgg-core = { path = "../smsgg-core" }
z80-emu = { path = "../../cpu/z80-emu" }

bincode = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
