const OPCODE_MNEMONICS: [&str; 256] = [
    "NOP",
    "LD BC, nn",
    "LD (BC), A",
    "INC BC",
    "INC B",
    "DEC B",
    "LD B, n",
    "RLCA",
    "EX AF, AF'",
    "ADD HL, BC",
    "LD A, (BC)",
    "DEC BC",
    "INC C",
    "DEC C",
    "LD C, n",
    "RRCA",
    "DJNZ d",
    "LD DE, nn",
    "LD (DE), A",
    "INC DE",
    "INC D",
    "DEC D",
    "LD D, n",
    "RLA",
    "JR d",
    "ADD HL, DE",
    "LD A, (DE)",
    "DEC DE",
    "INC E",
    "DEC E",
    "LD E, n",
    "RRA",
    "JR NZ, d",
    "LD HL, nn",
    "LD (nn), HL",
    "INC HL",
    "INC H",
    "DEC H",
    "LD H, n",
    "DAA",
    "JR Z, d",
    "ADD HL, HL",
    "LD HL, (nn)",
    "DEC HL",
    "INC L",
    "DEC L",
    "LD L, n",
    "CPL",
    "JR NC, d",
    "LD SP, nn",
    "LD (nn), A",
    "INC SP",
    "INC (HL)",
    "DEC (HL)",
    "LD (HL), n",
    "SCF",
    "JR C, d",
    "ADD HL, SP",
    "LD A, (nn)",
    "DEC SP",
    "INC A",
    "DEC A",
    "LD A, n",
    "CCF",
    "LD B, B",
    "LD B, C",
    "LD B, D",
    "LD B, E",
    "LD B, H",
    "LD B, L",
    "LD B, (HL)",
    "LD B, A",
    "LD C, B",
    "LD C, C",
    "LD C, D",
    "LD C, E",
    "LD C, H",
    "LD C, L",
    "LD C, (HL)",
    "LD C, A",
    "LD D, B",
    "LD D, C",
    "LD D, D",
    "LD D, E",
    "LD D, H",
    "LD D, L",
    "LD D, (HL)",
    "LD D, A",
    "LD E, B",
    "LD E, C",
    "LD E, D",
    "LD E, E",
    "LD E, H",
    "LD E, L",
    "LD E, (HL)",
    "LD E, A",
    "LD H, B",
    "LD H, C",
    "LD H, D",
    "LD H, E",
    "LD H, H",
    "LD H, L",
    "LD H, (HL)",
    "LD H, A",
    "LD L, B",
    "LD L, C",
    "LD L, D",
    "LD L, E",
    "LD L, H",
    "LD L, L",
    "LD L, (HL)",
    "LD L, A",
    "LD (HL), B",
    "LD (HL), C",
    "LD (HL), D",
    "LD (HL), E",
    "LD (HL), H",
    "LD (HL), L",
    "HALT",
    "LD (HL), A",
    "LD A, B",
    "LD A, C",
    "LD A, D",
    "LD A, E",
    "LD A, H",
    "LD A, L",
    "LD A, (HL)",
    "LD A, A",
    "ADD A, B",
    "ADD A, C",
    "ADD A, D",
    "ADD A, E",
    "ADD A, H",
    "ADD A, L",
    "ADD A, (HL)",
    "ADD A, A",
    "ADC A, B",
    "ADC A, C",
    "ADC A, D",
    "ADC A, E",
    "ADC A, H",
    "ADC A, L",
    "ADC A, (HL)",
    "ADC A, A",
    "SUB B",
    "SUB C",
    "SUB D",
    "SUB E",
    "SUB H",
    "SUB L",
    "SUB (HL)",
    "SUB A",
    "SBC A, B",
    "SBC A, C",
    "SBC A, D",
    "SBC A, E",
    "SBC A, H",
    "SBC A, L",
    "SBC A, (HL)",
    "SBC A, A",
    "AND B",
    "AND C",
    "AND D",
    "AND E",
    "AND H",
    "AND L",
    "AND (HL)",
    "AND A",
    "XOR B",
    "XOR C",
    "XOR D",
    "XOR E",
    "XOR H",
    "XOR L",
    "XOR (HL)",
    "XOR A",
    "OR B",
    "OR C",
    "OR D",
    "OR E",
    "OR H",
    "OR L",
    "OR (HL)",
    "OR A",
    "CP B",
    "CP C",
    "CP D",
    "CP E",
    "CP H",
    "CP L",
    "CP (HL)",
    "CP A",
    "RET NZ",
    "POP BC",
    "JP NZ, nn",
    "JP nn",
    "CALL NZ, nn",
    "PUSH BC",
    "ADD A, n",
    "RST $00",
    "RET Z",
    "RET",
    "JP Z, nn",
    "(bit prefix)",
    "CALL Z, nn",
    "CALL nn",
    "ADC A, n",
    "RST $08",
    "RET NC",
    "POP DE",
    "JP NC, nn",
    "OUT (n), A",
    "CALL NC, nn",
    "PUSH DE",
    "SUB n",
    "RST $10",
    "RET C",
    "EXX",
    "JP C, nn",
    "IN A, (n)",
    "CALL C, nn",
    "(IX prefix)",
    "SBC A, n",
    "RST $18",
    "RET PO",
    "POP HL",
    "JP PO, nn",
    "EX (SP), HL",
    "CALL PO, nn",
    "PUSH HL",
    "AND n",
    "RST $20",
    "RET PE",
    "JP (HL)",
    "JP PE, nn",
    "EX DE, HL",
    "CALL PE, nn",
    "(ED prefix)",
    "XOR n",
    "RST $28",
    "RET P",
    "POP AF",
    "JP P, nn",
    "DI",
    "CALL P, nn",
    "PUSH AF",
    "OR n",
    "RST $30",
    "RET M",
    "LD SP, HL",
    "JP M, nn",
    "EI",
    "CALL M, nn",
    "(IY prefix)",
    "CP n",
    "RST $38",
];

pub fn for_opcode(opcode: u8) -> &'static str {
    OPCODE_MNEMONICS[opcode as usize]
}
